name: An Introduction to Structure Validation
category: setup
authors: ""
shortdesc: This course will introduce methods to deduce that starting structures for preparing simulations represent high quality starting points.
longdesc: ""
